name: Trigger Medicine Reminder Cron

on:
  schedule:
    - cron: '* * * * *'

jobs:
  trigger-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel API for medicine reminders
        uses: actions/http-client@v1
        with:
          url: 'https://your-vercel-app.vercel.app/api/sendMedicineReminders'
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.CRON_SECRET }}
