name: Medicine Reminder Cron

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch:

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron Endpoint
        run: |
          curl -X POST "https://medicine-reminder-api.vercel.app/api/sendMedicineReminders" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"
